services:
  - type: web
    name: laravel-api
    env: docker
    repo: https://github.com/ataussamadansari/LostFinder-backend.git
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:CuzXLWpeC0TL3pe2S3iJnMYCBWZhvNeNd4ox+F2OU0k0=
      - key: APP_URL
        value: https://yourapp.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: lostfinder
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value:
